/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateCategoryPageInput = {
  id?: string | null,
  ProductType: string,
  Categories: Array< string >,
  PageTitle: string,
  PageSubtitle: string,
};

export type ModelCategoryPageConditionInput = {
  Categories?: ModelStringInput | null,
  PageTitle?: ModelStringInput | null,
  PageSubtitle?: ModelStringInput | null,
  and?: Array< ModelCategoryPageConditionInput | null > | null,
  or?: Array< ModelCategoryPageConditionInput | null > | null,
  not?: ModelCategoryPageConditionInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type CategoryPage = {
  __typename: "CategoryPage",
  id: string,
  ProductType: string,
  Categories: Array< string >,
  Listings?: ModelProductListingConnection | null,
  PageTitle: string,
  PageSubtitle: string,
  createdAt: string,
  updatedAt: string,
};

export type ModelProductListingConnection = {
  __typename: "ModelProductListingConnection",
  items:  Array<ProductListing | null >,
  nextToken?: string | null,
};

export type ProductListing = {
  __typename: "ProductListing",
  productId: string,
  ProductName: string,
  ProductType: string,
  BrandName: string,
  Rating: number,
  Description: string,
  ImageUrl: string,
  Categories: Array< string >,
  categoryPage?: CategoryPage | null,
  Rank: number,
  Tags?: ModelTagConnection | null,
  ReferralUrl?: ModelReferralUrlConnection | null,
  createdAt: string,
  updatedAt: string,
  categoryPageListingsId: string,
};

export type ModelTagConnection = {
  __typename: "ModelTagConnection",
  items:  Array<Tag | null >,
  nextToken?: string | null,
};

export type Tag = {
  __typename: "Tag",
  Label: string,
  Color: string,
  id: string,
  createdAt: string,
  updatedAt: string,
  productListingTagsId: string,
};

export type ModelReferralUrlConnection = {
  __typename: "ModelReferralUrlConnection",
  items:  Array<ReferralUrl | null >,
  nextToken?: string | null,
};

export type ReferralUrl = {
  __typename: "ReferralUrl",
  Url: string,
  Listing: ProductListing,
  id: string,
  createdAt: string,
  updatedAt: string,
  productListingReferralUrlId: string,
};

export type UpdateCategoryPageInput = {
  id?: string | null,
  ProductType: string,
  Categories?: Array< string > | null,
  PageTitle?: string | null,
  PageSubtitle?: string | null,
};

export type DeleteCategoryPageInput = {
  ProductType: string,
};

export type CreateProductListingInput = {
  productId: string,
  ProductName: string,
  ProductType: string,
  BrandName: string,
  Rating: number,
  Description: string,
  ImageUrl: string,
  Categories: Array< string >,
  Rank: number,
  categoryPageListingsId: string,
};

export type ModelProductListingConditionInput = {
  ProductName?: ModelStringInput | null,
  ProductType?: ModelStringInput | null,
  BrandName?: ModelStringInput | null,
  Rating?: ModelFloatInput | null,
  Description?: ModelStringInput | null,
  ImageUrl?: ModelStringInput | null,
  Categories?: ModelStringInput | null,
  Rank?: ModelIntInput | null,
  and?: Array< ModelProductListingConditionInput | null > | null,
  or?: Array< ModelProductListingConditionInput | null > | null,
  not?: ModelProductListingConditionInput | null,
  categoryPageListingsId?: ModelIDInput | null,
};

export type ModelFloatInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ModelIntInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type UpdateProductListingInput = {
  productId: string,
  ProductName?: string | null,
  ProductType?: string | null,
  BrandName?: string | null,
  Rating?: number | null,
  Description?: string | null,
  ImageUrl?: string | null,
  Categories?: Array< string > | null,
  Rank?: number | null,
  categoryPageListingsId?: string | null,
};

export type DeleteProductListingInput = {
  productId: string,
};

export type CreateTagInput = {
  Label: string,
  Color: string,
  id?: string | null,
  productListingTagsId: string,
};

export type ModelTagConditionInput = {
  Label?: ModelStringInput | null,
  Color?: ModelStringInput | null,
  and?: Array< ModelTagConditionInput | null > | null,
  or?: Array< ModelTagConditionInput | null > | null,
  not?: ModelTagConditionInput | null,
  productListingTagsId?: ModelIDInput | null,
};

export type UpdateTagInput = {
  Label?: string | null,
  Color?: string | null,
  id: string,
  productListingTagsId?: string | null,
};

export type DeleteTagInput = {
  id: string,
};

export type CreateReferralUrlInput = {
  Url: string,
  id?: string | null,
  productListingReferralUrlId: string,
};

export type ModelReferralUrlConditionInput = {
  Url?: ModelStringInput | null,
  and?: Array< ModelReferralUrlConditionInput | null > | null,
  or?: Array< ModelReferralUrlConditionInput | null > | null,
  not?: ModelReferralUrlConditionInput | null,
  productListingReferralUrlId?: ModelIDInput | null,
};

export type UpdateReferralUrlInput = {
  Url?: string | null,
  id: string,
  productListingReferralUrlId?: string | null,
};

export type DeleteReferralUrlInput = {
  id: string,
};

export type ModelCategoryPageFilterInput = {
  id?: ModelIDInput | null,
  ProductType?: ModelStringInput | null,
  Categories?: ModelStringInput | null,
  PageTitle?: ModelStringInput | null,
  PageSubtitle?: ModelStringInput | null,
  and?: Array< ModelCategoryPageFilterInput | null > | null,
  or?: Array< ModelCategoryPageFilterInput | null > | null,
  not?: ModelCategoryPageFilterInput | null,
};

export enum ModelSortDirection {
  ASC = "ASC",
  DESC = "DESC",
}


export type ModelCategoryPageConnection = {
  __typename: "ModelCategoryPageConnection",
  items:  Array<CategoryPage | null >,
  nextToken?: string | null,
};

export type ModelProductListingFilterInput = {
  productId?: ModelIDInput | null,
  ProductName?: ModelStringInput | null,
  ProductType?: ModelStringInput | null,
  BrandName?: ModelStringInput | null,
  Rating?: ModelFloatInput | null,
  Description?: ModelStringInput | null,
  ImageUrl?: ModelStringInput | null,
  Categories?: ModelStringInput | null,
  Rank?: ModelIntInput | null,
  and?: Array< ModelProductListingFilterInput | null > | null,
  or?: Array< ModelProductListingFilterInput | null > | null,
  not?: ModelProductListingFilterInput | null,
  categoryPageListingsId?: ModelIDInput | null,
};

export type ModelTagFilterInput = {
  Label?: ModelStringInput | null,
  Color?: ModelStringInput | null,
  and?: Array< ModelTagFilterInput | null > | null,
  or?: Array< ModelTagFilterInput | null > | null,
  not?: ModelTagFilterInput | null,
  productListingTagsId?: ModelIDInput | null,
};

export type ModelReferralUrlFilterInput = {
  Url?: ModelStringInput | null,
  and?: Array< ModelReferralUrlFilterInput | null > | null,
  or?: Array< ModelReferralUrlFilterInput | null > | null,
  not?: ModelReferralUrlFilterInput | null,
  productListingReferralUrlId?: ModelIDInput | null,
};

export type CreateCategoryPageMutationVariables = {
  input: CreateCategoryPageInput,
  condition?: ModelCategoryPageConditionInput | null,
};

export type CreateCategoryPageMutation = {
  createCategoryPage?:  {
    __typename: "CategoryPage",
    id: string,
    ProductType: string,
    Categories: Array< string >,
    Listings?:  {
      __typename: "ModelProductListingConnection",
      items:  Array< {
        __typename: "ProductListing",
        productId: string,
        ProductName: string,
        ProductType: string,
        BrandName: string,
        Rating: number,
        Description: string,
        ImageUrl: string,
        Categories: Array< string >,
        categoryPage?:  {
          __typename: "CategoryPage",
          id: string,
          ProductType: string,
          Categories: Array< string >,
          Listings?:  {
            __typename: "ModelProductListingConnection",
            nextToken?: string | null,
          } | null,
          PageTitle: string,
          PageSubtitle: string,
          createdAt: string,
          updatedAt: string,
        } | null,
        Rank: number,
        Tags?:  {
          __typename: "ModelTagConnection",
          items:  Array< {
            __typename: "Tag",
            Label: string,
            Color: string,
            id: string,
            createdAt: string,
            updatedAt: string,
            productListingTagsId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        ReferralUrl?:  {
          __typename: "ModelReferralUrlConnection",
          items:  Array< {
            __typename: "ReferralUrl",
            Url: string,
            id: string,
            createdAt: string,
            updatedAt: string,
            productListingReferralUrlId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        createdAt: string,
        updatedAt: string,
        categoryPageListingsId: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    PageTitle: string,
    PageSubtitle: string,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateCategoryPageMutationVariables = {
  input: UpdateCategoryPageInput,
  condition?: ModelCategoryPageConditionInput | null,
};

export type UpdateCategoryPageMutation = {
  updateCategoryPage?:  {
    __typename: "CategoryPage",
    id: string,
    ProductType: string,
    Categories: Array< string >,
    Listings?:  {
      __typename: "ModelProductListingConnection",
      items:  Array< {
        __typename: "ProductListing",
        productId: string,
        ProductName: string,
        ProductType: string,
        BrandName: string,
        Rating: number,
        Description: string,
        ImageUrl: string,
        Categories: Array< string >,
        categoryPage?:  {
          __typename: "CategoryPage",
          id: string,
          ProductType: string,
          Categories: Array< string >,
          Listings?:  {
            __typename: "ModelProductListingConnection",
            nextToken?: string | null,
          } | null,
          PageTitle: string,
          PageSubtitle: string,
          createdAt: string,
          updatedAt: string,
        } | null,
        Rank: number,
        Tags?:  {
          __typename: "ModelTagConnection",
          items:  Array< {
            __typename: "Tag",
            Label: string,
            Color: string,
            id: string,
            createdAt: string,
            updatedAt: string,
            productListingTagsId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        ReferralUrl?:  {
          __typename: "ModelReferralUrlConnection",
          items:  Array< {
            __typename: "ReferralUrl",
            Url: string,
            id: string,
            createdAt: string,
            updatedAt: string,
            productListingReferralUrlId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        createdAt: string,
        updatedAt: string,
        categoryPageListingsId: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    PageTitle: string,
    PageSubtitle: string,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteCategoryPageMutationVariables = {
  input: DeleteCategoryPageInput,
  condition?: ModelCategoryPageConditionInput | null,
};

export type DeleteCategoryPageMutation = {
  deleteCategoryPage?:  {
    __typename: "CategoryPage",
    id: string,
    ProductType: string,
    Categories: Array< string >,
    Listings?:  {
      __typename: "ModelProductListingConnection",
      items:  Array< {
        __typename: "ProductListing",
        productId: string,
        ProductName: string,
        ProductType: string,
        BrandName: string,
        Rating: number,
        Description: string,
        ImageUrl: string,
        Categories: Array< string >,
        categoryPage?:  {
          __typename: "CategoryPage",
          id: string,
          ProductType: string,
          Categories: Array< string >,
          Listings?:  {
            __typename: "ModelProductListingConnection",
            nextToken?: string | null,
          } | null,
          PageTitle: string,
          PageSubtitle: string,
          createdAt: string,
          updatedAt: string,
        } | null,
        Rank: number,
        Tags?:  {
          __typename: "ModelTagConnection",
          items:  Array< {
            __typename: "Tag",
            Label: string,
            Color: string,
            id: string,
            createdAt: string,
            updatedAt: string,
            productListingTagsId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        ReferralUrl?:  {
          __typename: "ModelReferralUrlConnection",
          items:  Array< {
            __typename: "ReferralUrl",
            Url: string,
            id: string,
            createdAt: string,
            updatedAt: string,
            productListingReferralUrlId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        createdAt: string,
        updatedAt: string,
        categoryPageListingsId: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    PageTitle: string,
    PageSubtitle: string,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreateProductListingMutationVariables = {
  input: CreateProductListingInput,
  condition?: ModelProductListingConditionInput | null,
};

export type CreateProductListingMutation = {
  createProductListing?:  {
    __typename: "ProductListing",
    productId: string,
    ProductName: string,
    ProductType: string,
    BrandName: string,
    Rating: number,
    Description: string,
    ImageUrl: string,
    Categories: Array< string >,
    categoryPage?:  {
      __typename: "CategoryPage",
      id: string,
      ProductType: string,
      Categories: Array< string >,
      Listings?:  {
        __typename: "ModelProductListingConnection",
        items:  Array< {
          __typename: "ProductListing",
          productId: string,
          ProductName: string,
          ProductType: string,
          BrandName: string,
          Rating: number,
          Description: string,
          ImageUrl: string,
          Categories: Array< string >,
          categoryPage?:  {
            __typename: "CategoryPage",
            id: string,
            ProductType: string,
            Categories: Array< string >,
            PageTitle: string,
            PageSubtitle: string,
            createdAt: string,
            updatedAt: string,
          } | null,
          Rank: number,
          Tags?:  {
            __typename: "ModelTagConnection",
            nextToken?: string | null,
          } | null,
          ReferralUrl?:  {
            __typename: "ModelReferralUrlConnection",
            nextToken?: string | null,
          } | null,
          createdAt: string,
          updatedAt: string,
          categoryPageListingsId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      PageTitle: string,
      PageSubtitle: string,
      createdAt: string,
      updatedAt: string,
    } | null,
    Rank: number,
    Tags?:  {
      __typename: "ModelTagConnection",
      items:  Array< {
        __typename: "Tag",
        Label: string,
        Color: string,
        id: string,
        createdAt: string,
        updatedAt: string,
        productListingTagsId: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    ReferralUrl?:  {
      __typename: "ModelReferralUrlConnection",
      items:  Array< {
        __typename: "ReferralUrl",
        Url: string,
        Listing:  {
          __typename: "ProductListing",
          productId: string,
          ProductName: string,
          ProductType: string,
          BrandName: string,
          Rating: number,
          Description: string,
          ImageUrl: string,
          Categories: Array< string >,
          categoryPage?:  {
            __typename: "CategoryPage",
            id: string,
            ProductType: string,
            Categories: Array< string >,
            PageTitle: string,
            PageSubtitle: string,
            createdAt: string,
            updatedAt: string,
          } | null,
          Rank: number,
          Tags?:  {
            __typename: "ModelTagConnection",
            nextToken?: string | null,
          } | null,
          ReferralUrl?:  {
            __typename: "ModelReferralUrlConnection",
            nextToken?: string | null,
          } | null,
          createdAt: string,
          updatedAt: string,
          categoryPageListingsId: string,
        },
        id: string,
        createdAt: string,
        updatedAt: string,
        productListingReferralUrlId: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    categoryPageListingsId: string,
  } | null,
};

export type UpdateProductListingMutationVariables = {
  input: UpdateProductListingInput,
  condition?: ModelProductListingConditionInput | null,
};

export type UpdateProductListingMutation = {
  updateProductListing?:  {
    __typename: "ProductListing",
    productId: string,
    ProductName: string,
    ProductType: string,
    BrandName: string,
    Rating: number,
    Description: string,
    ImageUrl: string,
    Categories: Array< string >,
    categoryPage?:  {
      __typename: "CategoryPage",
      id: string,
      ProductType: string,
      Categories: Array< string >,
      Listings?:  {
        __typename: "ModelProductListingConnection",
        items:  Array< {
          __typename: "ProductListing",
          productId: string,
          ProductName: string,
          ProductType: string,
          BrandName: string,
          Rating: number,
          Description: string,
          ImageUrl: string,
          Categories: Array< string >,
          categoryPage?:  {
            __typename: "CategoryPage",
            id: string,
            ProductType: string,
            Categories: Array< string >,
            PageTitle: string,
            PageSubtitle: string,
            createdAt: string,
            updatedAt: string,
          } | null,
          Rank: number,
          Tags?:  {
            __typename: "ModelTagConnection",
            nextToken?: string | null,
          } | null,
          ReferralUrl?:  {
            __typename: "ModelReferralUrlConnection",
            nextToken?: string | null,
          } | null,
          createdAt: string,
          updatedAt: string,
          categoryPageListingsId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      PageTitle: string,
      PageSubtitle: string,
      createdAt: string,
      updatedAt: string,
    } | null,
    Rank: number,
    Tags?:  {
      __typename: "ModelTagConnection",
      items:  Array< {
        __typename: "Tag",
        Label: string,
        Color: string,
        id: string,
        createdAt: string,
        updatedAt: string,
        productListingTagsId: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    ReferralUrl?:  {
      __typename: "ModelReferralUrlConnection",
      items:  Array< {
        __typename: "ReferralUrl",
        Url: string,
        Listing:  {
          __typename: "ProductListing",
          productId: string,
          ProductName: string,
          ProductType: string,
          BrandName: string,
          Rating: number,
          Description: string,
          ImageUrl: string,
          Categories: Array< string >,
          categoryPage?:  {
            __typename: "CategoryPage",
            id: string,
            ProductType: string,
            Categories: Array< string >,
            PageTitle: string,
            PageSubtitle: string,
            createdAt: string,
            updatedAt: string,
          } | null,
          Rank: number,
          Tags?:  {
            __typename: "ModelTagConnection",
            nextToken?: string | null,
          } | null,
          ReferralUrl?:  {
            __typename: "ModelReferralUrlConnection",
            nextToken?: string | null,
          } | null,
          createdAt: string,
          updatedAt: string,
          categoryPageListingsId: string,
        },
        id: string,
        createdAt: string,
        updatedAt: string,
        productListingReferralUrlId: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    categoryPageListingsId: string,
  } | null,
};

export type DeleteProductListingMutationVariables = {
  input: DeleteProductListingInput,
  condition?: ModelProductListingConditionInput | null,
};

export type DeleteProductListingMutation = {
  deleteProductListing?:  {
    __typename: "ProductListing",
    productId: string,
    ProductName: string,
    ProductType: string,
    BrandName: string,
    Rating: number,
    Description: string,
    ImageUrl: string,
    Categories: Array< string >,
    categoryPage?:  {
      __typename: "CategoryPage",
      id: string,
      ProductType: string,
      Categories: Array< string >,
      Listings?:  {
        __typename: "ModelProductListingConnection",
        items:  Array< {
          __typename: "ProductListing",
          productId: string,
          ProductName: string,
          ProductType: string,
          BrandName: string,
          Rating: number,
          Description: string,
          ImageUrl: string,
          Categories: Array< string >,
          categoryPage?:  {
            __typename: "CategoryPage",
            id: string,
            ProductType: string,
            Categories: Array< string >,
            PageTitle: string,
            PageSubtitle: string,
            createdAt: string,
            updatedAt: string,
          } | null,
          Rank: number,
          Tags?:  {
            __typename: "ModelTagConnection",
            nextToken?: string | null,
          } | null,
          ReferralUrl?:  {
            __typename: "ModelReferralUrlConnection",
            nextToken?: string | null,
          } | null,
          createdAt: string,
          updatedAt: string,
          categoryPageListingsId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      PageTitle: string,
      PageSubtitle: string,
      createdAt: string,
      updatedAt: string,
    } | null,
    Rank: number,
    Tags?:  {
      __typename: "ModelTagConnection",
      items:  Array< {
        __typename: "Tag",
        Label: string,
        Color: string,
        id: string,
        createdAt: string,
        updatedAt: string,
        productListingTagsId: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    ReferralUrl?:  {
      __typename: "ModelReferralUrlConnection",
      items:  Array< {
        __typename: "ReferralUrl",
        Url: string,
        Listing:  {
          __typename: "ProductListing",
          productId: string,
          ProductName: string,
          ProductType: string,
          BrandName: string,
          Rating: number,
          Description: string,
          ImageUrl: string,
          Categories: Array< string >,
          categoryPage?:  {
            __typename: "CategoryPage",
            id: string,
            ProductType: string,
            Categories: Array< string >,
            PageTitle: string,
            PageSubtitle: string,
            createdAt: string,
            updatedAt: string,
          } | null,
          Rank: number,
          Tags?:  {
            __typename: "ModelTagConnection",
            nextToken?: string | null,
          } | null,
          ReferralUrl?:  {
            __typename: "ModelReferralUrlConnection",
            nextToken?: string | null,
          } | null,
          createdAt: string,
          updatedAt: string,
          categoryPageListingsId: string,
        },
        id: string,
        createdAt: string,
        updatedAt: string,
        productListingReferralUrlId: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    categoryPageListingsId: string,
  } | null,
};

export type CreateTagMutationVariables = {
  input: CreateTagInput,
  condition?: ModelTagConditionInput | null,
};

export type CreateTagMutation = {
  createTag?:  {
    __typename: "Tag",
    Label: string,
    Color: string,
    id: string,
    createdAt: string,
    updatedAt: string,
    productListingTagsId: string,
  } | null,
};

export type UpdateTagMutationVariables = {
  input: UpdateTagInput,
  condition?: ModelTagConditionInput | null,
};

export type UpdateTagMutation = {
  updateTag?:  {
    __typename: "Tag",
    Label: string,
    Color: string,
    id: string,
    createdAt: string,
    updatedAt: string,
    productListingTagsId: string,
  } | null,
};

export type DeleteTagMutationVariables = {
  input: DeleteTagInput,
  condition?: ModelTagConditionInput | null,
};

export type DeleteTagMutation = {
  deleteTag?:  {
    __typename: "Tag",
    Label: string,
    Color: string,
    id: string,
    createdAt: string,
    updatedAt: string,
    productListingTagsId: string,
  } | null,
};

export type CreateReferralUrlMutationVariables = {
  input: CreateReferralUrlInput,
  condition?: ModelReferralUrlConditionInput | null,
};

export type CreateReferralUrlMutation = {
  createReferralUrl?:  {
    __typename: "ReferralUrl",
    Url: string,
    Listing:  {
      __typename: "ProductListing",
      productId: string,
      ProductName: string,
      ProductType: string,
      BrandName: string,
      Rating: number,
      Description: string,
      ImageUrl: string,
      Categories: Array< string >,
      categoryPage?:  {
        __typename: "CategoryPage",
        id: string,
        ProductType: string,
        Categories: Array< string >,
        Listings?:  {
          __typename: "ModelProductListingConnection",
          items:  Array< {
            __typename: "ProductListing",
            productId: string,
            ProductName: string,
            ProductType: string,
            BrandName: string,
            Rating: number,
            Description: string,
            ImageUrl: string,
            Categories: Array< string >,
            Rank: number,
            createdAt: string,
            updatedAt: string,
            categoryPageListingsId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        PageTitle: string,
        PageSubtitle: string,
        createdAt: string,
        updatedAt: string,
      } | null,
      Rank: number,
      Tags?:  {
        __typename: "ModelTagConnection",
        items:  Array< {
          __typename: "Tag",
          Label: string,
          Color: string,
          id: string,
          createdAt: string,
          updatedAt: string,
          productListingTagsId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      ReferralUrl?:  {
        __typename: "ModelReferralUrlConnection",
        items:  Array< {
          __typename: "ReferralUrl",
          Url: string,
          Listing:  {
            __typename: "ProductListing",
            productId: string,
            ProductName: string,
            ProductType: string,
            BrandName: string,
            Rating: number,
            Description: string,
            ImageUrl: string,
            Categories: Array< string >,
            Rank: number,
            createdAt: string,
            updatedAt: string,
            categoryPageListingsId: string,
          },
          id: string,
          createdAt: string,
          updatedAt: string,
          productListingReferralUrlId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      categoryPageListingsId: string,
    },
    id: string,
    createdAt: string,
    updatedAt: string,
    productListingReferralUrlId: string,
  } | null,
};

export type UpdateReferralUrlMutationVariables = {
  input: UpdateReferralUrlInput,
  condition?: ModelReferralUrlConditionInput | null,
};

export type UpdateReferralUrlMutation = {
  updateReferralUrl?:  {
    __typename: "ReferralUrl",
    Url: string,
    Listing:  {
      __typename: "ProductListing",
      productId: string,
      ProductName: string,
      ProductType: string,
      BrandName: string,
      Rating: number,
      Description: string,
      ImageUrl: string,
      Categories: Array< string >,
      categoryPage?:  {
        __typename: "CategoryPage",
        id: string,
        ProductType: string,
        Categories: Array< string >,
        Listings?:  {
          __typename: "ModelProductListingConnection",
          items:  Array< {
            __typename: "ProductListing",
            productId: string,
            ProductName: string,
            ProductType: string,
            BrandName: string,
            Rating: number,
            Description: string,
            ImageUrl: string,
            Categories: Array< string >,
            Rank: number,
            createdAt: string,
            updatedAt: string,
            categoryPageListingsId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        PageTitle: string,
        PageSubtitle: string,
        createdAt: string,
        updatedAt: string,
      } | null,
      Rank: number,
      Tags?:  {
        __typename: "ModelTagConnection",
        items:  Array< {
          __typename: "Tag",
          Label: string,
          Color: string,
          id: string,
          createdAt: string,
          updatedAt: string,
          productListingTagsId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      ReferralUrl?:  {
        __typename: "ModelReferralUrlConnection",
        items:  Array< {
          __typename: "ReferralUrl",
          Url: string,
          Listing:  {
            __typename: "ProductListing",
            productId: string,
            ProductName: string,
            ProductType: string,
            BrandName: string,
            Rating: number,
            Description: string,
            ImageUrl: string,
            Categories: Array< string >,
            Rank: number,
            createdAt: string,
            updatedAt: string,
            categoryPageListingsId: string,
          },
          id: string,
          createdAt: string,
          updatedAt: string,
          productListingReferralUrlId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      categoryPageListingsId: string,
    },
    id: string,
    createdAt: string,
    updatedAt: string,
    productListingReferralUrlId: string,
  } | null,
};

export type DeleteReferralUrlMutationVariables = {
  input: DeleteReferralUrlInput,
  condition?: ModelReferralUrlConditionInput | null,
};

export type DeleteReferralUrlMutation = {
  deleteReferralUrl?:  {
    __typename: "ReferralUrl",
    Url: string,
    Listing:  {
      __typename: "ProductListing",
      productId: string,
      ProductName: string,
      ProductType: string,
      BrandName: string,
      Rating: number,
      Description: string,
      ImageUrl: string,
      Categories: Array< string >,
      categoryPage?:  {
        __typename: "CategoryPage",
        id: string,
        ProductType: string,
        Categories: Array< string >,
        Listings?:  {
          __typename: "ModelProductListingConnection",
          items:  Array< {
            __typename: "ProductListing",
            productId: string,
            ProductName: string,
            ProductType: string,
            BrandName: string,
            Rating: number,
            Description: string,
            ImageUrl: string,
            Categories: Array< string >,
            Rank: number,
            createdAt: string,
            updatedAt: string,
            categoryPageListingsId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        PageTitle: string,
        PageSubtitle: string,
        createdAt: string,
        updatedAt: string,
      } | null,
      Rank: number,
      Tags?:  {
        __typename: "ModelTagConnection",
        items:  Array< {
          __typename: "Tag",
          Label: string,
          Color: string,
          id: string,
          createdAt: string,
          updatedAt: string,
          productListingTagsId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      ReferralUrl?:  {
        __typename: "ModelReferralUrlConnection",
        items:  Array< {
          __typename: "ReferralUrl",
          Url: string,
          Listing:  {
            __typename: "ProductListing",
            productId: string,
            ProductName: string,
            ProductType: string,
            BrandName: string,
            Rating: number,
            Description: string,
            ImageUrl: string,
            Categories: Array< string >,
            Rank: number,
            createdAt: string,
            updatedAt: string,
            categoryPageListingsId: string,
          },
          id: string,
          createdAt: string,
          updatedAt: string,
          productListingReferralUrlId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      categoryPageListingsId: string,
    },
    id: string,
    createdAt: string,
    updatedAt: string,
    productListingReferralUrlId: string,
  } | null,
};

export type GetCategoryPageQueryVariables = {
  ProductType: string,
};

export type GetCategoryPageQuery = {
  getCategoryPage?:  {
    __typename: "CategoryPage",
    id: string,
    ProductType: string,
    Categories: Array< string >,
    Listings?:  {
      __typename: "ModelProductListingConnection",
      items:  Array< {
        __typename: "ProductListing",
        productId: string,
        ProductName: string,
        ProductType: string,
        BrandName: string,
        Rating: number,
        Description: string,
        ImageUrl: string,
        Categories: Array< string >,
        categoryPage?:  {
          __typename: "CategoryPage",
          id: string,
          ProductType: string,
          Categories: Array< string >,
          Listings?:  {
            __typename: "ModelProductListingConnection",
            nextToken?: string | null,
          } | null,
          PageTitle: string,
          PageSubtitle: string,
          createdAt: string,
          updatedAt: string,
        } | null,
        Rank: number,
        Tags?:  {
          __typename: "ModelTagConnection",
          items:  Array< {
            __typename: "Tag",
            Label: string,
            Color: string,
            id: string,
            createdAt: string,
            updatedAt: string,
            productListingTagsId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        ReferralUrl?:  {
          __typename: "ModelReferralUrlConnection",
          items:  Array< {
            __typename: "ReferralUrl",
            Url: string,
            id: string,
            createdAt: string,
            updatedAt: string,
            productListingReferralUrlId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        createdAt: string,
        updatedAt: string,
        categoryPageListingsId: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    PageTitle: string,
    PageSubtitle: string,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListCategoryPagesQueryVariables = {
  ProductType?: string | null,
  filter?: ModelCategoryPageFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  sortDirection?: ModelSortDirection | null,
};

export type ListCategoryPagesQuery = {
  listCategoryPages?:  {
    __typename: "ModelCategoryPageConnection",
    items:  Array< {
      __typename: "CategoryPage",
      id: string,
      ProductType: string,
      Categories: Array< string >,
      Listings?:  {
        __typename: "ModelProductListingConnection",
        items:  Array< {
          __typename: "ProductListing",
          productId: string,
          ProductName: string,
          ProductType: string,
          BrandName: string,
          Rating: number,
          Description: string,
          ImageUrl: string,
          Categories: Array< string >,
          categoryPage?:  {
            __typename: "CategoryPage",
            id: string,
            ProductType: string,
            Categories: Array< string >,
            PageTitle: string,
            PageSubtitle: string,
            createdAt: string,
            updatedAt: string,
          } | null,
          Rank: number,
          Tags?:  {
            __typename: "ModelTagConnection",
            nextToken?: string | null,
          } | null,
          ReferralUrl?:  {
            __typename: "ModelReferralUrlConnection",
            nextToken?: string | null,
          } | null,
          createdAt: string,
          updatedAt: string,
          categoryPageListingsId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      PageTitle: string,
      PageSubtitle: string,
      createdAt: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type GetProductListingQueryVariables = {
  productId: string,
};

export type GetProductListingQuery = {
  getProductListing?:  {
    __typename: "ProductListing",
    productId: string,
    ProductName: string,
    ProductType: string,
    BrandName: string,
    Rating: number,
    Description: string,
    ImageUrl: string,
    Categories: Array< string >,
    categoryPage?:  {
      __typename: "CategoryPage",
      id: string,
      ProductType: string,
      Categories: Array< string >,
      Listings?:  {
        __typename: "ModelProductListingConnection",
        items:  Array< {
          __typename: "ProductListing",
          productId: string,
          ProductName: string,
          ProductType: string,
          BrandName: string,
          Rating: number,
          Description: string,
          ImageUrl: string,
          Categories: Array< string >,
          categoryPage?:  {
            __typename: "CategoryPage",
            id: string,
            ProductType: string,
            Categories: Array< string >,
            PageTitle: string,
            PageSubtitle: string,
            createdAt: string,
            updatedAt: string,
          } | null,
          Rank: number,
          Tags?:  {
            __typename: "ModelTagConnection",
            nextToken?: string | null,
          } | null,
          ReferralUrl?:  {
            __typename: "ModelReferralUrlConnection",
            nextToken?: string | null,
          } | null,
          createdAt: string,
          updatedAt: string,
          categoryPageListingsId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      PageTitle: string,
      PageSubtitle: string,
      createdAt: string,
      updatedAt: string,
    } | null,
    Rank: number,
    Tags?:  {
      __typename: "ModelTagConnection",
      items:  Array< {
        __typename: "Tag",
        Label: string,
        Color: string,
        id: string,
        createdAt: string,
        updatedAt: string,
        productListingTagsId: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    ReferralUrl?:  {
      __typename: "ModelReferralUrlConnection",
      items:  Array< {
        __typename: "ReferralUrl",
        Url: string,
        Listing:  {
          __typename: "ProductListing",
          productId: string,
          ProductName: string,
          ProductType: string,
          BrandName: string,
          Rating: number,
          Description: string,
          ImageUrl: string,
          Categories: Array< string >,
          categoryPage?:  {
            __typename: "CategoryPage",
            id: string,
            ProductType: string,
            Categories: Array< string >,
            PageTitle: string,
            PageSubtitle: string,
            createdAt: string,
            updatedAt: string,
          } | null,
          Rank: number,
          Tags?:  {
            __typename: "ModelTagConnection",
            nextToken?: string | null,
          } | null,
          ReferralUrl?:  {
            __typename: "ModelReferralUrlConnection",
            nextToken?: string | null,
          } | null,
          createdAt: string,
          updatedAt: string,
          categoryPageListingsId: string,
        },
        id: string,
        createdAt: string,
        updatedAt: string,
        productListingReferralUrlId: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    categoryPageListingsId: string,
  } | null,
};

export type ListProductListingsQueryVariables = {
  productId?: string | null,
  filter?: ModelProductListingFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  sortDirection?: ModelSortDirection | null,
};

export type ListProductListingsQuery = {
  listProductListings?:  {
    __typename: "ModelProductListingConnection",
    items:  Array< {
      __typename: "ProductListing",
      productId: string,
      ProductName: string,
      ProductType: string,
      BrandName: string,
      Rating: number,
      Description: string,
      ImageUrl: string,
      Categories: Array< string >,
      categoryPage?:  {
        __typename: "CategoryPage",
        id: string,
        ProductType: string,
        Categories: Array< string >,
        Listings?:  {
          __typename: "ModelProductListingConnection",
          items:  Array< {
            __typename: "ProductListing",
            productId: string,
            ProductName: string,
            ProductType: string,
            BrandName: string,
            Rating: number,
            Description: string,
            ImageUrl: string,
            Categories: Array< string >,
            Rank: number,
            createdAt: string,
            updatedAt: string,
            categoryPageListingsId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        PageTitle: string,
        PageSubtitle: string,
        createdAt: string,
        updatedAt: string,
      } | null,
      Rank: number,
      Tags?:  {
        __typename: "ModelTagConnection",
        items:  Array< {
          __typename: "Tag",
          Label: string,
          Color: string,
          id: string,
          createdAt: string,
          updatedAt: string,
          productListingTagsId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      ReferralUrl?:  {
        __typename: "ModelReferralUrlConnection",
        items:  Array< {
          __typename: "ReferralUrl",
          Url: string,
          Listing:  {
            __typename: "ProductListing",
            productId: string,
            ProductName: string,
            ProductType: string,
            BrandName: string,
            Rating: number,
            Description: string,
            ImageUrl: string,
            Categories: Array< string >,
            Rank: number,
            createdAt: string,
            updatedAt: string,
            categoryPageListingsId: string,
          },
          id: string,
          createdAt: string,
          updatedAt: string,
          productListingReferralUrlId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      categoryPageListingsId: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type GetTagQueryVariables = {
  id: string,
};

export type GetTagQuery = {
  getTag?:  {
    __typename: "Tag",
    Label: string,
    Color: string,
    id: string,
    createdAt: string,
    updatedAt: string,
    productListingTagsId: string,
  } | null,
};

export type ListTagsQueryVariables = {
  filter?: ModelTagFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListTagsQuery = {
  listTags?:  {
    __typename: "ModelTagConnection",
    items:  Array< {
      __typename: "Tag",
      Label: string,
      Color: string,
      id: string,
      createdAt: string,
      updatedAt: string,
      productListingTagsId: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type GetReferralUrlQueryVariables = {
  id: string,
};

export type GetReferralUrlQuery = {
  getReferralUrl?:  {
    __typename: "ReferralUrl",
    Url: string,
    Listing:  {
      __typename: "ProductListing",
      productId: string,
      ProductName: string,
      ProductType: string,
      BrandName: string,
      Rating: number,
      Description: string,
      ImageUrl: string,
      Categories: Array< string >,
      categoryPage?:  {
        __typename: "CategoryPage",
        id: string,
        ProductType: string,
        Categories: Array< string >,
        Listings?:  {
          __typename: "ModelProductListingConnection",
          items:  Array< {
            __typename: "ProductListing",
            productId: string,
            ProductName: string,
            ProductType: string,
            BrandName: string,
            Rating: number,
            Description: string,
            ImageUrl: string,
            Categories: Array< string >,
            Rank: number,
            createdAt: string,
            updatedAt: string,
            categoryPageListingsId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        PageTitle: string,
        PageSubtitle: string,
        createdAt: string,
        updatedAt: string,
      } | null,
      Rank: number,
      Tags?:  {
        __typename: "ModelTagConnection",
        items:  Array< {
          __typename: "Tag",
          Label: string,
          Color: string,
          id: string,
          createdAt: string,
          updatedAt: string,
          productListingTagsId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      ReferralUrl?:  {
        __typename: "ModelReferralUrlConnection",
        items:  Array< {
          __typename: "ReferralUrl",
          Url: string,
          Listing:  {
            __typename: "ProductListing",
            productId: string,
            ProductName: string,
            ProductType: string,
            BrandName: string,
            Rating: number,
            Description: string,
            ImageUrl: string,
            Categories: Array< string >,
            Rank: number,
            createdAt: string,
            updatedAt: string,
            categoryPageListingsId: string,
          },
          id: string,
          createdAt: string,
          updatedAt: string,
          productListingReferralUrlId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      categoryPageListingsId: string,
    },
    id: string,
    createdAt: string,
    updatedAt: string,
    productListingReferralUrlId: string,
  } | null,
};

export type ListReferralUrlsQueryVariables = {
  filter?: ModelReferralUrlFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListReferralUrlsQuery = {
  listReferralUrls?:  {
    __typename: "ModelReferralUrlConnection",
    items:  Array< {
      __typename: "ReferralUrl",
      Url: string,
      Listing:  {
        __typename: "ProductListing",
        productId: string,
        ProductName: string,
        ProductType: string,
        BrandName: string,
        Rating: number,
        Description: string,
        ImageUrl: string,
        Categories: Array< string >,
        categoryPage?:  {
          __typename: "CategoryPage",
          id: string,
          ProductType: string,
          Categories: Array< string >,
          Listings?:  {
            __typename: "ModelProductListingConnection",
            nextToken?: string | null,
          } | null,
          PageTitle: string,
          PageSubtitle: string,
          createdAt: string,
          updatedAt: string,
        } | null,
        Rank: number,
        Tags?:  {
          __typename: "ModelTagConnection",
          items:  Array< {
            __typename: "Tag",
            Label: string,
            Color: string,
            id: string,
            createdAt: string,
            updatedAt: string,
            productListingTagsId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        ReferralUrl?:  {
          __typename: "ModelReferralUrlConnection",
          items:  Array< {
            __typename: "ReferralUrl",
            Url: string,
            id: string,
            createdAt: string,
            updatedAt: string,
            productListingReferralUrlId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        createdAt: string,
        updatedAt: string,
        categoryPageListingsId: string,
      },
      id: string,
      createdAt: string,
      updatedAt: string,
      productListingReferralUrlId: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type OnCreateCategoryPageSubscription = {
  onCreateCategoryPage?:  {
    __typename: "CategoryPage",
    id: string,
    ProductType: string,
    Categories: Array< string >,
    Listings?:  {
      __typename: "ModelProductListingConnection",
      items:  Array< {
        __typename: "ProductListing",
        productId: string,
        ProductName: string,
        ProductType: string,
        BrandName: string,
        Rating: number,
        Description: string,
        ImageUrl: string,
        Categories: Array< string >,
        categoryPage?:  {
          __typename: "CategoryPage",
          id: string,
          ProductType: string,
          Categories: Array< string >,
          Listings?:  {
            __typename: "ModelProductListingConnection",
            nextToken?: string | null,
          } | null,
          PageTitle: string,
          PageSubtitle: string,
          createdAt: string,
          updatedAt: string,
        } | null,
        Rank: number,
        Tags?:  {
          __typename: "ModelTagConnection",
          items:  Array< {
            __typename: "Tag",
            Label: string,
            Color: string,
            id: string,
            createdAt: string,
            updatedAt: string,
            productListingTagsId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        ReferralUrl?:  {
          __typename: "ModelReferralUrlConnection",
          items:  Array< {
            __typename: "ReferralUrl",
            Url: string,
            id: string,
            createdAt: string,
            updatedAt: string,
            productListingReferralUrlId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        createdAt: string,
        updatedAt: string,
        categoryPageListingsId: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    PageTitle: string,
    PageSubtitle: string,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateCategoryPageSubscription = {
  onUpdateCategoryPage?:  {
    __typename: "CategoryPage",
    id: string,
    ProductType: string,
    Categories: Array< string >,
    Listings?:  {
      __typename: "ModelProductListingConnection",
      items:  Array< {
        __typename: "ProductListing",
        productId: string,
        ProductName: string,
        ProductType: string,
        BrandName: string,
        Rating: number,
        Description: string,
        ImageUrl: string,
        Categories: Array< string >,
        categoryPage?:  {
          __typename: "CategoryPage",
          id: string,
          ProductType: string,
          Categories: Array< string >,
          Listings?:  {
            __typename: "ModelProductListingConnection",
            nextToken?: string | null,
          } | null,
          PageTitle: string,
          PageSubtitle: string,
          createdAt: string,
          updatedAt: string,
        } | null,
        Rank: number,
        Tags?:  {
          __typename: "ModelTagConnection",
          items:  Array< {
            __typename: "Tag",
            Label: string,
            Color: string,
            id: string,
            createdAt: string,
            updatedAt: string,
            productListingTagsId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        ReferralUrl?:  {
          __typename: "ModelReferralUrlConnection",
          items:  Array< {
            __typename: "ReferralUrl",
            Url: string,
            id: string,
            createdAt: string,
            updatedAt: string,
            productListingReferralUrlId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        createdAt: string,
        updatedAt: string,
        categoryPageListingsId: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    PageTitle: string,
    PageSubtitle: string,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteCategoryPageSubscription = {
  onDeleteCategoryPage?:  {
    __typename: "CategoryPage",
    id: string,
    ProductType: string,
    Categories: Array< string >,
    Listings?:  {
      __typename: "ModelProductListingConnection",
      items:  Array< {
        __typename: "ProductListing",
        productId: string,
        ProductName: string,
        ProductType: string,
        BrandName: string,
        Rating: number,
        Description: string,
        ImageUrl: string,
        Categories: Array< string >,
        categoryPage?:  {
          __typename: "CategoryPage",
          id: string,
          ProductType: string,
          Categories: Array< string >,
          Listings?:  {
            __typename: "ModelProductListingConnection",
            nextToken?: string | null,
          } | null,
          PageTitle: string,
          PageSubtitle: string,
          createdAt: string,
          updatedAt: string,
        } | null,
        Rank: number,
        Tags?:  {
          __typename: "ModelTagConnection",
          items:  Array< {
            __typename: "Tag",
            Label: string,
            Color: string,
            id: string,
            createdAt: string,
            updatedAt: string,
            productListingTagsId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        ReferralUrl?:  {
          __typename: "ModelReferralUrlConnection",
          items:  Array< {
            __typename: "ReferralUrl",
            Url: string,
            id: string,
            createdAt: string,
            updatedAt: string,
            productListingReferralUrlId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        createdAt: string,
        updatedAt: string,
        categoryPageListingsId: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    PageTitle: string,
    PageSubtitle: string,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreateProductListingSubscription = {
  onCreateProductListing?:  {
    __typename: "ProductListing",
    productId: string,
    ProductName: string,
    ProductType: string,
    BrandName: string,
    Rating: number,
    Description: string,
    ImageUrl: string,
    Categories: Array< string >,
    categoryPage?:  {
      __typename: "CategoryPage",
      id: string,
      ProductType: string,
      Categories: Array< string >,
      Listings?:  {
        __typename: "ModelProductListingConnection",
        items:  Array< {
          __typename: "ProductListing",
          productId: string,
          ProductName: string,
          ProductType: string,
          BrandName: string,
          Rating: number,
          Description: string,
          ImageUrl: string,
          Categories: Array< string >,
          categoryPage?:  {
            __typename: "CategoryPage",
            id: string,
            ProductType: string,
            Categories: Array< string >,
            PageTitle: string,
            PageSubtitle: string,
            createdAt: string,
            updatedAt: string,
          } | null,
          Rank: number,
          Tags?:  {
            __typename: "ModelTagConnection",
            nextToken?: string | null,
          } | null,
          ReferralUrl?:  {
            __typename: "ModelReferralUrlConnection",
            nextToken?: string | null,
          } | null,
          createdAt: string,
          updatedAt: string,
          categoryPageListingsId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      PageTitle: string,
      PageSubtitle: string,
      createdAt: string,
      updatedAt: string,
    } | null,
    Rank: number,
    Tags?:  {
      __typename: "ModelTagConnection",
      items:  Array< {
        __typename: "Tag",
        Label: string,
        Color: string,
        id: string,
        createdAt: string,
        updatedAt: string,
        productListingTagsId: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    ReferralUrl?:  {
      __typename: "ModelReferralUrlConnection",
      items:  Array< {
        __typename: "ReferralUrl",
        Url: string,
        Listing:  {
          __typename: "ProductListing",
          productId: string,
          ProductName: string,
          ProductType: string,
          BrandName: string,
          Rating: number,
          Description: string,
          ImageUrl: string,
          Categories: Array< string >,
          categoryPage?:  {
            __typename: "CategoryPage",
            id: string,
            ProductType: string,
            Categories: Array< string >,
            PageTitle: string,
            PageSubtitle: string,
            createdAt: string,
            updatedAt: string,
          } | null,
          Rank: number,
          Tags?:  {
            __typename: "ModelTagConnection",
            nextToken?: string | null,
          } | null,
          ReferralUrl?:  {
            __typename: "ModelReferralUrlConnection",
            nextToken?: string | null,
          } | null,
          createdAt: string,
          updatedAt: string,
          categoryPageListingsId: string,
        },
        id: string,
        createdAt: string,
        updatedAt: string,
        productListingReferralUrlId: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    categoryPageListingsId: string,
  } | null,
};

export type OnUpdateProductListingSubscription = {
  onUpdateProductListing?:  {
    __typename: "ProductListing",
    productId: string,
    ProductName: string,
    ProductType: string,
    BrandName: string,
    Rating: number,
    Description: string,
    ImageUrl: string,
    Categories: Array< string >,
    categoryPage?:  {
      __typename: "CategoryPage",
      id: string,
      ProductType: string,
      Categories: Array< string >,
      Listings?:  {
        __typename: "ModelProductListingConnection",
        items:  Array< {
          __typename: "ProductListing",
          productId: string,
          ProductName: string,
          ProductType: string,
          BrandName: string,
          Rating: number,
          Description: string,
          ImageUrl: string,
          Categories: Array< string >,
          categoryPage?:  {
            __typename: "CategoryPage",
            id: string,
            ProductType: string,
            Categories: Array< string >,
            PageTitle: string,
            PageSubtitle: string,
            createdAt: string,
            updatedAt: string,
          } | null,
          Rank: number,
          Tags?:  {
            __typename: "ModelTagConnection",
            nextToken?: string | null,
          } | null,
          ReferralUrl?:  {
            __typename: "ModelReferralUrlConnection",
            nextToken?: string | null,
          } | null,
          createdAt: string,
          updatedAt: string,
          categoryPageListingsId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      PageTitle: string,
      PageSubtitle: string,
      createdAt: string,
      updatedAt: string,
    } | null,
    Rank: number,
    Tags?:  {
      __typename: "ModelTagConnection",
      items:  Array< {
        __typename: "Tag",
        Label: string,
        Color: string,
        id: string,
        createdAt: string,
        updatedAt: string,
        productListingTagsId: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    ReferralUrl?:  {
      __typename: "ModelReferralUrlConnection",
      items:  Array< {
        __typename: "ReferralUrl",
        Url: string,
        Listing:  {
          __typename: "ProductListing",
          productId: string,
          ProductName: string,
          ProductType: string,
          BrandName: string,
          Rating: number,
          Description: string,
          ImageUrl: string,
          Categories: Array< string >,
          categoryPage?:  {
            __typename: "CategoryPage",
            id: string,
            ProductType: string,
            Categories: Array< string >,
            PageTitle: string,
            PageSubtitle: string,
            createdAt: string,
            updatedAt: string,
          } | null,
          Rank: number,
          Tags?:  {
            __typename: "ModelTagConnection",
            nextToken?: string | null,
          } | null,
          ReferralUrl?:  {
            __typename: "ModelReferralUrlConnection",
            nextToken?: string | null,
          } | null,
          createdAt: string,
          updatedAt: string,
          categoryPageListingsId: string,
        },
        id: string,
        createdAt: string,
        updatedAt: string,
        productListingReferralUrlId: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    categoryPageListingsId: string,
  } | null,
};

export type OnDeleteProductListingSubscription = {
  onDeleteProductListing?:  {
    __typename: "ProductListing",
    productId: string,
    ProductName: string,
    ProductType: string,
    BrandName: string,
    Rating: number,
    Description: string,
    ImageUrl: string,
    Categories: Array< string >,
    categoryPage?:  {
      __typename: "CategoryPage",
      id: string,
      ProductType: string,
      Categories: Array< string >,
      Listings?:  {
        __typename: "ModelProductListingConnection",
        items:  Array< {
          __typename: "ProductListing",
          productId: string,
          ProductName: string,
          ProductType: string,
          BrandName: string,
          Rating: number,
          Description: string,
          ImageUrl: string,
          Categories: Array< string >,
          categoryPage?:  {
            __typename: "CategoryPage",
            id: string,
            ProductType: string,
            Categories: Array< string >,
            PageTitle: string,
            PageSubtitle: string,
            createdAt: string,
            updatedAt: string,
          } | null,
          Rank: number,
          Tags?:  {
            __typename: "ModelTagConnection",
            nextToken?: string | null,
          } | null,
          ReferralUrl?:  {
            __typename: "ModelReferralUrlConnection",
            nextToken?: string | null,
          } | null,
          createdAt: string,
          updatedAt: string,
          categoryPageListingsId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      PageTitle: string,
      PageSubtitle: string,
      createdAt: string,
      updatedAt: string,
    } | null,
    Rank: number,
    Tags?:  {
      __typename: "ModelTagConnection",
      items:  Array< {
        __typename: "Tag",
        Label: string,
        Color: string,
        id: string,
        createdAt: string,
        updatedAt: string,
        productListingTagsId: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    ReferralUrl?:  {
      __typename: "ModelReferralUrlConnection",
      items:  Array< {
        __typename: "ReferralUrl",
        Url: string,
        Listing:  {
          __typename: "ProductListing",
          productId: string,
          ProductName: string,
          ProductType: string,
          BrandName: string,
          Rating: number,
          Description: string,
          ImageUrl: string,
          Categories: Array< string >,
          categoryPage?:  {
            __typename: "CategoryPage",
            id: string,
            ProductType: string,
            Categories: Array< string >,
            PageTitle: string,
            PageSubtitle: string,
            createdAt: string,
            updatedAt: string,
          } | null,
          Rank: number,
          Tags?:  {
            __typename: "ModelTagConnection",
            nextToken?: string | null,
          } | null,
          ReferralUrl?:  {
            __typename: "ModelReferralUrlConnection",
            nextToken?: string | null,
          } | null,
          createdAt: string,
          updatedAt: string,
          categoryPageListingsId: string,
        },
        id: string,
        createdAt: string,
        updatedAt: string,
        productListingReferralUrlId: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    categoryPageListingsId: string,
  } | null,
};

export type OnCreateTagSubscription = {
  onCreateTag?:  {
    __typename: "Tag",
    Label: string,
    Color: string,
    id: string,
    createdAt: string,
    updatedAt: string,
    productListingTagsId: string,
  } | null,
};

export type OnUpdateTagSubscription = {
  onUpdateTag?:  {
    __typename: "Tag",
    Label: string,
    Color: string,
    id: string,
    createdAt: string,
    updatedAt: string,
    productListingTagsId: string,
  } | null,
};

export type OnDeleteTagSubscription = {
  onDeleteTag?:  {
    __typename: "Tag",
    Label: string,
    Color: string,
    id: string,
    createdAt: string,
    updatedAt: string,
    productListingTagsId: string,
  } | null,
};

export type OnCreateReferralUrlSubscription = {
  onCreateReferralUrl?:  {
    __typename: "ReferralUrl",
    Url: string,
    Listing:  {
      __typename: "ProductListing",
      productId: string,
      ProductName: string,
      ProductType: string,
      BrandName: string,
      Rating: number,
      Description: string,
      ImageUrl: string,
      Categories: Array< string >,
      categoryPage?:  {
        __typename: "CategoryPage",
        id: string,
        ProductType: string,
        Categories: Array< string >,
        Listings?:  {
          __typename: "ModelProductListingConnection",
          items:  Array< {
            __typename: "ProductListing",
            productId: string,
            ProductName: string,
            ProductType: string,
            BrandName: string,
            Rating: number,
            Description: string,
            ImageUrl: string,
            Categories: Array< string >,
            Rank: number,
            createdAt: string,
            updatedAt: string,
            categoryPageListingsId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        PageTitle: string,
        PageSubtitle: string,
        createdAt: string,
        updatedAt: string,
      } | null,
      Rank: number,
      Tags?:  {
        __typename: "ModelTagConnection",
        items:  Array< {
          __typename: "Tag",
          Label: string,
          Color: string,
          id: string,
          createdAt: string,
          updatedAt: string,
          productListingTagsId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      ReferralUrl?:  {
        __typename: "ModelReferralUrlConnection",
        items:  Array< {
          __typename: "ReferralUrl",
          Url: string,
          Listing:  {
            __typename: "ProductListing",
            productId: string,
            ProductName: string,
            ProductType: string,
            BrandName: string,
            Rating: number,
            Description: string,
            ImageUrl: string,
            Categories: Array< string >,
            Rank: number,
            createdAt: string,
            updatedAt: string,
            categoryPageListingsId: string,
          },
          id: string,
          createdAt: string,
          updatedAt: string,
          productListingReferralUrlId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      categoryPageListingsId: string,
    },
    id: string,
    createdAt: string,
    updatedAt: string,
    productListingReferralUrlId: string,
  } | null,
};

export type OnUpdateReferralUrlSubscription = {
  onUpdateReferralUrl?:  {
    __typename: "ReferralUrl",
    Url: string,
    Listing:  {
      __typename: "ProductListing",
      productId: string,
      ProductName: string,
      ProductType: string,
      BrandName: string,
      Rating: number,
      Description: string,
      ImageUrl: string,
      Categories: Array< string >,
      categoryPage?:  {
        __typename: "CategoryPage",
        id: string,
        ProductType: string,
        Categories: Array< string >,
        Listings?:  {
          __typename: "ModelProductListingConnection",
          items:  Array< {
            __typename: "ProductListing",
            productId: string,
            ProductName: string,
            ProductType: string,
            BrandName: string,
            Rating: number,
            Description: string,
            ImageUrl: string,
            Categories: Array< string >,
            Rank: number,
            createdAt: string,
            updatedAt: string,
            categoryPageListingsId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        PageTitle: string,
        PageSubtitle: string,
        createdAt: string,
        updatedAt: string,
      } | null,
      Rank: number,
      Tags?:  {
        __typename: "ModelTagConnection",
        items:  Array< {
          __typename: "Tag",
          Label: string,
          Color: string,
          id: string,
          createdAt: string,
          updatedAt: string,
          productListingTagsId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      ReferralUrl?:  {
        __typename: "ModelReferralUrlConnection",
        items:  Array< {
          __typename: "ReferralUrl",
          Url: string,
          Listing:  {
            __typename: "ProductListing",
            productId: string,
            ProductName: string,
            ProductType: string,
            BrandName: string,
            Rating: number,
            Description: string,
            ImageUrl: string,
            Categories: Array< string >,
            Rank: number,
            createdAt: string,
            updatedAt: string,
            categoryPageListingsId: string,
          },
          id: string,
          createdAt: string,
          updatedAt: string,
          productListingReferralUrlId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      categoryPageListingsId: string,
    },
    id: string,
    createdAt: string,
    updatedAt: string,
    productListingReferralUrlId: string,
  } | null,
};

export type OnDeleteReferralUrlSubscription = {
  onDeleteReferralUrl?:  {
    __typename: "ReferralUrl",
    Url: string,
    Listing:  {
      __typename: "ProductListing",
      productId: string,
      ProductName: string,
      ProductType: string,
      BrandName: string,
      Rating: number,
      Description: string,
      ImageUrl: string,
      Categories: Array< string >,
      categoryPage?:  {
        __typename: "CategoryPage",
        id: string,
        ProductType: string,
        Categories: Array< string >,
        Listings?:  {
          __typename: "ModelProductListingConnection",
          items:  Array< {
            __typename: "ProductListing",
            productId: string,
            ProductName: string,
            ProductType: string,
            BrandName: string,
            Rating: number,
            Description: string,
            ImageUrl: string,
            Categories: Array< string >,
            Rank: number,
            createdAt: string,
            updatedAt: string,
            categoryPageListingsId: string,
          } | null >,
          nextToken?: string | null,
        } | null,
        PageTitle: string,
        PageSubtitle: string,
        createdAt: string,
        updatedAt: string,
      } | null,
      Rank: number,
      Tags?:  {
        __typename: "ModelTagConnection",
        items:  Array< {
          __typename: "Tag",
          Label: string,
          Color: string,
          id: string,
          createdAt: string,
          updatedAt: string,
          productListingTagsId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      ReferralUrl?:  {
        __typename: "ModelReferralUrlConnection",
        items:  Array< {
          __typename: "ReferralUrl",
          Url: string,
          Listing:  {
            __typename: "ProductListing",
            productId: string,
            ProductName: string,
            ProductType: string,
            BrandName: string,
            Rating: number,
            Description: string,
            ImageUrl: string,
            Categories: Array< string >,
            Rank: number,
            createdAt: string,
            updatedAt: string,
            categoryPageListingsId: string,
          },
          id: string,
          createdAt: string,
          updatedAt: string,
          productListingReferralUrlId: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      categoryPageListingsId: string,
    },
    id: string,
    createdAt: string,
    updatedAt: string,
    productListingReferralUrlId: string,
  } | null,
};
